parameters:
  - name: action
    type: string
  - name: environment
    type: string

jobs:
  - job: TerraformJob
    displayName: "Terraform ${{ parameters.action }} (${{ parameters.environment }})"
    pool:
      name: aws_host
    steps:
      - checkout: self

      # Only run if not doing 'lint' (since we already know the tflint path)
      - ${{ if ne(parameters.action, 'lint') }}:
          - script: |
              if ! command -v tflint &> /dev/null; then
                echo "Installing tflint..."
                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              else
                echo "tflint already installed"
                tflint --version
              fi
            displayName: "Ensure tflint is installed"

      - ${{ if eq(parameters.action, 'fmt') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform fmt -check -recursive
            displayName: "Terraform Format Check"

      - ${{ if eq(parameters.action, 'lint') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              "C:\ProgramData\chocolatey\bin\tflint.exe" --recursive
            displayName: "Terraform Lint Check"

      - ${{ if or(eq(parameters.action, 'plan'), eq(parameters.action, 'apply')) }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform init
            displayName: "Terraform Init"

      - ${{ if eq(parameters.action, 'plan') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform plan -var-file=${{ parameters.environment }}.tfvars
            displayName: "Terraform Plan"

      - ${{ if eq(parameters.action, 'apply') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform apply -auto-approve -var-file=${{ parameters.environment }}.tfvars
            displayName: "Terraform Apply"
            condition: eq(variables['Build.Reason'], 'Manual')
