parameters:
  - name: action
    type: string
  - name: environment
    type: string

jobs:
  - job: Terragrunt_${{ parameters.environment }}_{{ parameters.action }}
    displayName: "Terragrunt ${{ parameters.action }} (${{ parameters.environment }})"
    pool:
      name: aws_host
    steps:
      - checkout: self

      - script: |
          cd terragrunt/${{ parameters.environment }}
          terragrunt plan-all
        displayName: "Terragrunt Plan-All"
        condition: eq(parameters.action, 'plan')

      - script: |
          cd terragrunt/${{ parameters.environment }}
          terragrunt apply-all -auto-approve
        displayName: "Terragrunt Apply-All"
        condition: and(eq(parameters.action, 'apply'), eq(variables['Build.Reason'], 'Manual'))
