# .azure/templates/terraform-template.yml
parameters:
  - name: action
    type: string
  - name: environment
    type: string

jobs:
  - job: TerraformJob
    displayName: "Terraform ${{ parameters.action }} (${{ parameters.environment }})"
    pool:
      name: aws-agent
    steps:
      - checkout: self

      - script: |
          cd envs/${{ parameters.environment }}
          terraform init
        displayName: "Terraform Init"

      - ${{ if eq(parameters.action, 'plan') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform plan -var-file=${{ parameters.environment }}.tfvars
            displayName: "Terraform Plan"

      - ${{ if eq(parameters.action, 'apply') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform apply -auto-approve -var-file=${{ parameters.environment }}.tfvars
            displayName: "Terraform Apply"
            condition: eq(variables['Build.Reason'], 'Manual')
