parameters:
  - name: action
    type: string
  - name: environment
    type: string

jobs:
  - job: TerraformJob
    displayName: "Terraform ${{ parameters.action }} (${{ parameters.environment }})"
    pool:
      name: aws-agent
    steps:
      - checkout: self

      - script: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        displayName: "Install tflint"

      - ${{ if eq(parameters.action, 'fmt') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform fmt -check -recursive
            displayName: "Terraform Format Check"

      - ${{ if eq(parameters.action, 'lint') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              tflint --recursive
            displayName: "Terraform Lint Check"

      - ${{ if or(eq(parameters.action, 'plan'), eq(parameters.action, 'apply')) }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform init
            displayName: "Terraform Init"

      - ${{ if eq(parameters.action, 'plan') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform plan -var-file=${{ parameters.environment }}.tfvars
            displayName: "Terraform Plan"

      - ${{ if eq(parameters.action, 'apply') }}:
          - script: |
              cd envs/${{ parameters.environment }}
              terraform apply -auto-approve -var-file=${{ parameters.environment }}.tfvars
            displayName: "Terraform Apply"
            condition: eq(variables['Build.Reason'], 'Manual')
