trigger:
  branches:
    include:
      - main

stages:
  - stage: Terraform_Dev
    displayName: "Terraform Dev"
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "plan"
          environment: "dev"

  - stage: Terraform_Prod
    displayName: "Terraform Prod"
    dependsOn: Terraform_Dev
    condition: succeeded()
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "plan"
          environment: "prod"

  - stage: Terragrunt_Dev
    displayName: "Terragrunt Dev"
    dependsOn: Terraform_Prod
    condition: succeeded()
    jobs:
      - template: templates/terragrunt-template.yml
        parameters:
          action: "plan"
          environment: "dev"

  - stage: Terragrunt_Prod
    displayName: "Terragrunt Prod"
    dependsOn: Terragrunt_Dev
    condition: succeeded()
    jobs:
      - template: templates/terragrunt-template.yml
        parameters:
          action: "plan"
          environment: "prod"
