trigger:
  branches:
    include:
      - main

stages:
  # -------------------------------
  # TERRAFORM DEV
  # -------------------------------
  - stage: Terraform_Dev_Fmt
    displayName: "Terraform Dev - Format"
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "fmt"
          environment: "dev"

  - stage: Terraform_Dev_Lint
    displayName: "Terraform Dev - Lint"
    dependsOn: Terraform_Dev_Fmt
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "lint"
          environment: "dev"

  - stage: Terraform_Dev_Plan
    displayName: "Terraform Dev - Plan"
    dependsOn: Terraform_Dev_Lint
    condition: succeeded()
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "plan"
          environment: "dev"

  # -------------------------------
  # TERRAFORM PROD
  # -------------------------------
  - stage: Terraform_Prod_Fmt
    displayName: "Terraform Prod - Format"
    dependsOn: Terraform_Dev_Plan
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "fmt"
          environment: "prod"

  - stage: Terraform_Prod_Lint
    displayName: "Terraform Prod - Lint"
    dependsOn: Terraform_Prod_Fmt
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "lint"
          environment: "prod"

  - stage: Terraform_Prod_Plan
    displayName: "Terraform Prod - Plan"
    dependsOn: Terraform_Prod_Lint
    condition: succeeded()
    jobs:
      - template: templates/terraform-template.yml
        parameters:
          action: "plan"
          environment: "prod"

  # -------------------------------
  # TERRAGRUNT DEV
  # -------------------------------
  - stage: Terragrunt_Dev_Fmt
    displayName: "Terragrunt Dev - Format"
    dependsOn: Terraform_Prod_Plan
    jobs:
      - template: templates/terragrunt-template.yml
        parameters:
          action: "fmt"
          environment: "dev"

  - stage: Terragrunt_Dev_Plan
    displayName: "Terragrunt Dev - Plan"
    dependsOn: Terragrunt_Dev_Fmt
    condition: succeeded()
    jobs:
      - template: templates/terragrunt-template.yml
        parameters:
          action: "plan"
          environment: "dev"

  # -------------------------------
  # TERRAGRUNT PROD
  # -------------------------------
  - stage: Terragrunt_Prod_Fmt
    displayName: "Terragrunt Prod - Format"
    dependsOn: Terragrunt_Dev_Plan
    jobs:
      - template: templates/terragrunt-template.yml
        parameters:
          action: "fmt"
          environment: "prod"

  - stage: Terragrunt_Prod_Plan
    displayName: "Terragrunt Prod - Plan"
    dependsOn: Terragrunt_Prod_Fmt
    condition: succeeded()
    jobs:
      - template: templates/terragrunt-template.yml
        parameters:
          action: "plan"
          environment: "prod"
